### ISSUE TITLE
Error posting

### ISSUE THREAD

**Issue by wellkunnected** [Squeegy/latest-chatty-2#132]
Hello,

I ran this app on my iPhone 6 Plus and am getting an error each time I try to post something. I've set a username and password but can't seem to post anything. If this code modified to work with iOS 9.2? Thanks in advance for your help.

**Comment by patch-e** [comment]
It sounds like you aren't already a registered Shacknews.com user? You can't just enter any username/password you want in the settings of the app. You must first register on the Shacknews.com website and then enter those credentials into the app to be able to post.
